### ISSUE TITLE
Can't search for spell solely by name

### ISSUE THREAD

**Issue by JamieRL** [eepMoody/open5e-api#49]
Not sure if this intended or not. Since the search fields on the spell viewset are:
`search_fields = ['dnd_class', 'name']`
When I went to search for the spell "druidcraft" by
/?search=druid 
It will return all druid spells.
I think ideally search for spells would only search by name since we can already filter by dnd_class
as in the spell filters
`'dnd_class': ['iexact', 'exact', 'in', 'icontains'],`

So I would propose removing 'dnd_class' from the search fields.

Let me know if I'm misunderstanding something

**Comment by eepMoody** [comment]
I originally set this up because there were some issues doing "contains" matches through the filters, but you're right that it's redundant?

This is limited to just the one spell though, right? As far as I know there aren't any other spells that contain a class name, and deprecating something like this risks breaking something for anyone using it. For such a unique edge case that feels a little risky to me.

**Comment by JamieRL** [comment]
Ok. That makes sense to me. I’ll close the issue.
